"""
Knowledge Base Loader
Loads and retrieves information from preprocessed embeddings.
Reads chunk and vector files generated by generate_embeddings.py
Can load from FAISS index, .pkl embeddings, or both.
"""

import os
import pickle
import glob
from generate_embeddings import EmbeddingProcessor


class KnowledgeBaseLoader:
    """
    Main class to load and query the knowledge base.
    Loads pre-generated embeddings (FAISS indices, .pkl files, and chunk text) 
    from files created by generate_embeddings.py
    """

    def __init__(self, model_name=None, output_dir=None):
        """Initialize KB loader with embedding processor and retriever
        
        Args:
            model_name: Name of sentence transformer model
            output_dir: Directory containing embeddings (default: output_embeddings in same folder)
        """
        if output_dir is None:
            output_dir = os.path.join(os.path.dirname(__file__), "output_embeddings")
        
        # Initialize the processor which handles the FAISS loading and searching
        self.processor = EmbeddingProcessor(model_name=model_name, output_dir=output_dir)
        self.output_dir = output_dir

    def load_embeddings_pkl(self, save_name, verbose=True):
        """
        Load embeddings from .pkl file.
        
        Args:
            save_name: Base name of saved files (e.g., "combined_embedded")
            verbose: Print progress
            
        Returns:
            numpy array of embeddings (float32)
        """
        pkl_path = os.path.join(self.output_dir, f"{save_name}.pkl")
        
        if not os.path.exists(pkl_path):
            raise FileNotFoundError(f"ไม่พบไฟล์ embeddings: {pkl_path}")
        
        with open(pkl_path, "rb") as f:
            embeddings = pickle.load(f)
        
        if verbose:
            print(f"Loaded embeddings from {pkl_path}")
            print(f"Shape: {embeddings.shape}")
        
        return embeddings

    def load_chunks(self, save_name, verbose=True):
        """
        Load chunks from text file.
        
        Args:
            save_name: Base name of saved files (e.g., "combined_embedded")
            verbose: Print progress
            
        Returns:
            List of chunk strings
        """
        chunks_path = os.path.join(self.output_dir, f"{save_name}_chunk.txt")
        
        if not os.path.exists(chunks_path):
            raise FileNotFoundError(f"ไม่พบไฟล์ chunks: {chunks_path}")
        
        with open(chunks_path, "r", encoding="utf-8") as f:
            raw = f.read().strip()
        
        # Split by --- that we defined in generate_embeddings.py
        chunks = [c.strip() for c in raw.split("\n---\n") if c.strip()]
        
        if verbose:
            print(f"Loaded {len(chunks)} chunks from {chunks_path}")
        
        return chunks

    def load_all(self, save_name, verbose=True):
        """
        Load all files (embeddings + chunks) for a knowledge base.
        """
        embeddings = self.load_embeddings_pkl(save_name, verbose=verbose)
        chunks = self.load_chunks(save_name, verbose=verbose)
        
        return embeddings, chunks

    def list_available_embeddings(self):
        """List all available embedding sets in output_embeddings folder"""
        pkl_files = glob.glob(os.path.join(self.output_dir, "*.pkl"))
        
        available = []
        for pkl_file in sorted(pkl_files):
            basename = os.path.basename(pkl_file)
            save_name = basename.replace(".pkl", "")
            available.append(save_name)
        
        return available

    def load_embeddings(self, save_name, copy_to_ascii=None, verbose=True):
        """
        Load pre-generated embeddings and chunks from disk (FAISS index).
        """
        index, chunks = self.processor.load_index_and_chunks(
            save_name,
            copy_to_ascii=copy_to_ascii
        )
        if verbose:
            print(f"Loaded {len(chunks)} chunks from {save_name}")
        return index, chunks

    def search(self, query, save_name, top_k=5):
        """
        Search combined knowledge base using FAISS index
        """
        return self.processor.search(
            query=query,
            save_name=save_name,
            top_k=top_k
        )

    def print_results(self, results, query):
        """Pretty print search results"""
        print(f"\n{'='*60}")
        print(f"Query: {query}")
        print(f"{'='*60}")

        if results:
            for i, r in enumerate(results, 1):
                print(f"\n[{i}] (Distance/Score: {r['distance']:.4f})")
                
                # Split the chunk into lines to format it nicely
                # Since we inject [SOURCE] and [หมวดหมู่] at the top, we want to see them clearly
                chunk_lines = r['chunk'].split('\n')
                
                # Highlight source and category tags if they exist
                for line in chunk_lines:
                    if line.startswith("[SOURCE:"):
                        print(f"    📍 {line}")
                    elif line.startswith("[หมวดหมู่:"):
                        print(f"    🏷️ {line}")
                    elif line.strip(): # Normal text line
                        print(f"    {line}")
                print("-" * 40)
        else:
            print("No results found")


if __name__ == "__main__":
    # Example usage - Load and use embeddings
    kb = KnowledgeBaseLoader()

    print("=" * 60)
    print("Available Embedding Sets:")
    print("=" * 60)
    available = kb.list_available_embeddings()
    if available:
        for i, name in enumerate(available, 1):
            print(f"[{i}] {name}")
    else:
        print("ไม่พบไฟล์ embeddings ในโฟลเดอร์ output_embeddings")
        exit(1)

    print("\n" + "=" * 60)
    print("Example 1: Load embeddings and chunks from .pkl file")
    print("=" * 60)
    try:
        # Load from pickle file (recommended for external use)
        embeddings, chunks = kb.load_all("combined_embedded")
        print(f"\n✓ Loaded successfully")
        print(f"  - Embeddings shape: {embeddings.shape}")
        print(f"  - Number of chunks: {len(chunks)}")
        
        print(f"\nFirst chunk preview:")
        # Show more context in preview
        preview_text = chunks[0][:300].replace('\n', ' ')
        print(f"  {preview_text}...")
    except Exception as e:
        print(f"✗ Error: {e}")

    print("\n" + "=" * 60)
    print("Example 2: Search using query (FAISS index)")
    print("=" * 60)
    try:
        # Search using FAISS index (Try a query that causes confusion to test Context Tag)
        test_query = "ปี 1 เทอม 1 ต้องเรียนวิชาอะไรบ้าง"
        results = kb.search(test_query, save_name="combined_embedded", top_k=3)
        kb.print_results(results, test_query)

    except Exception as e:
        print(f"✗ Error: {e}")