"""
Knowledge Base Loader (Smart Router Edition)
Loads and retrieves information from preprocessed embeddings.
Reads chunk and vector files generated by generate_embeddings.py
*** มาพร้อมระบบ Metadata Filtering (ดักจับ Keyword เพื่อกรองหมวดหมู่อัตโนมัติ) ***
"""

import os
import pickle
import glob
import numpy as np
from database.embeddings.generate_embeddings import EmbeddingProcessor


class KnowledgeBaseLoader:
    """
    Main class to load and query the knowledge base.
    """

    def __init__(self, model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2", output_dir=None):
        """Initialize KB loader
        * เปลี่ยนมาใช้โมเดล multilingual เพื่อให้รองรับภาษาไทย 100% *
        """
        if output_dir is None:
            output_dir = os.path.join(os.path.dirname(__file__), "output_embeddings")
        
        # Initialize the processor
        self.processor = EmbeddingProcessor(model_name=model_name, output_dir=output_dir)
        self.output_dir = output_dir
        
        # ตัวแปรสำหรับเก็บข้อมูลไว้ใน Memory เพื่อให้ค้นหาได้ไวขึ้น
        self.index = None
        self.chunks = None
        self.embeddings = None
        self.loaded_name = None

    def load_embeddings_pkl(self, save_name, verbose=True):
        pkl_path = os.path.join(self.output_dir, f"{save_name}.pkl")
        if not os.path.exists(pkl_path):
            raise FileNotFoundError(f"ไม่พบไฟล์ embeddings: {pkl_path}")
        with open(pkl_path, "rb") as f:
            embeddings = pickle.load(f)
        return embeddings

    def load_chunks(self, save_name, verbose=True):
        chunks_path = os.path.join(self.output_dir, f"{save_name}_chunk.txt")
        if not os.path.exists(chunks_path):
            raise FileNotFoundError(f"ไม่พบไฟล์ chunks: {chunks_path}")
        with open(chunks_path, "r", encoding="utf-8") as f:
            raw = f.read().strip()
        chunks = [c.strip() for c in raw.split("\n---\n") if c.strip()]
        return chunks

    def load_system(self, save_name="combined_embedded", verbose=True):
        """โหลด FAISS, Chunks และ Numpy Array เข้า Memory (เรียกครั้งเดียวตอนเริ่มระบบ)"""
        self.index, self.chunks = self.processor.load_index_and_chunks(save_name)
        self.embeddings = self.load_embeddings_pkl(save_name, verbose=False)
        self.loaded_name = save_name
        if verbose:
            print(f"✅ System Loaded: {len(self.chunks)} chunks ready.")

    # ===============================
    # QUERY ROUTER (ตัวสับรางคำถาม)
    # ===============================
    # ===============================
    # QUERY ROUTER (ตัวสับรางคำถาม) - UPDATED
    # ===============================
    def detect_category(self, query):
        """ฟังก์ชันดักจับ Keyword ในคำถาม เพื่อเจาะจงหมวดหมู่ที่จะค้นหา (ปรับปรุงให้ยืดหยุ่นขึ้น)"""
        q = query.lower()
        
        # 1. หมวดอาจารย์ (ชัดเจนสุด)
        if any(word in q for word in ["อาจารย์", "อจ", "ผู้สอน", "ดร.", "รศ.", "ผศ.", "สอน", "อจ."]):
            return "[หมวดหมู่: ข้อมูลอาจารย์และบุคลากร]"
            
        # 2. หมวดค่าเทอม (ชัดเจนสุด)
        elif any(word in q for word in ["ค่าเทอม", "จ่าย", "กยศ", "กู้", "กี่บาท", "ค่าใช้จ่าย", "แพง", "เท่าไหร่", "เท่าไร"]):
            return "[หมวดหมู่: ค่าเทอมและการเงิน]"
            
        # 3. หมวดสหกิจ/ฝึกงาน
        elif any(word in q for word in ["สหกิจ", "ฝึกงาน", "co-op", "สถานที่ฝึกงาน"]):
            return "[หมวดหมู่: สหกิจศึกษา/การฝึกงาน]"
            
        # 4. หมวดบริษัท MOU
        elif any(word in q for word in ["บริษัท", "mou", "พาร์ทเนอร์", "พันธมิตร"]):
            return "[หมวดหมู่: เครือข่ายบริษัท/MOU]"
            
        # 5. หมวดแผนการเรียน vs คำอธิบายรายวิชา (อันนี้ซับซ้อนสุด ต้องแยกให้ดี)
        # ถ้ามีคำว่า ปี หรือ เทอม ให้ไปหาที่ 'แผนการเรียน' ก่อนเสมอ
        elif any(word in q for word in ["ปี 1", "ปี 2", "ปี 3", "ปี 4", "เทอม 1", "เทอม 2", "รุ่น"]):
            return "[หมวดหมู่: แผนการเรียน/โครงสร้างหลักสูตร]"
            
        # ถ้าถามถึงเนื้อหาข้างในวิชา หรือรหัสวิชาตรงๆ ค่อยไปหาที่ 'คำอธิบายรายวิชา'
        elif any(word in q for word in ["เรียนเกี่ยวกับ", "คือวิชาอะไร", "รหัสวิชา", "aie", "ma", "ph"]):
            return "[หมวดหมู่: รายวิชาและคำอธิบายรายวิชา]"
            
        # 6. หมวดข้อมูลทั่วไป (อาชีพ, แนวทาง)
        elif any(word in q for word in ["จบไป", "ทำงานอะไร", "อาชีพ", "ภาพรวม"]):
            return "[หมวดหมู่: ข้อมูลทั่วไป]"
            
        # 7. ถ้าไม่เข้าพวกเลย ปล่อยให้ FAISS จัดการแบบอิสระ
        return None

    # ===============================
    # SMART SEARCH
    # ===============================
    def search(self, query, save_name="combined_embedded", top_k=5):
        """
        ฟังก์ชันหลักที่เพื่อนคุณจะเรียกใช้
        มันจะตรวจเช็ค Keyword และกรองไฟล์ให้อัตโนมัติ!
        """
        # โหลดข้อมูลอัตโนมัติถ้ายังไม่ได้โหลด
        if self.loaded_name != save_name or self.chunks is None:
            self.load_system(save_name, verbose=False)

        # 1. แปลงคำถามเป็น Vector
        q_vec = self.processor.model.encode([query]).astype("float32")
        
        # 2. ตรวจสอบหมวดหมู่จากคำถาม
        target_category = self.detect_category(query)

        # 3. โหมดกรองหมวดหมู่ (เมื่อเจอ Keyword)
        if target_category and self.embeddings is not None:
            # หา index ของ chunk ทั้งหมดที่มี Tag ตรงกับที่ระบุ
            valid_indices = [i for i, chunk in enumerate(self.chunks) if target_category in chunk]
            
            if valid_indices:
                filtered_embeddings = self.embeddings[valid_indices]
                # คำนวณระยะห่าง L2 Distance ด้วย Numpy
                distances = np.linalg.norm(filtered_embeddings - q_vec, axis=1)
                
                # เรียงลำดับตัวที่คะแนนดีที่สุด
                best_relative_idx = np.argsort(distances)[:top_k]
                
                results = []
                for idx in best_relative_idx:
                    original_idx = valid_indices[idx]
                    results.append({
                        "distance": float(distances[idx]),
                        "chunk": self.chunks[original_idx]
                    })
                return results

        # 4. โหมดปกติ (เมื่อไม่เจอ Keyword ให้หาจากทั้งหมดผ่าน FAISS)
        D, I = self.index.search(q_vec, top_k)
        results = []
        for dist, idx in zip(D[0], I[0]):
            if 0 <= idx < len(self.chunks):
                results.append({
                    "distance": float(dist),
                    "chunk": self.chunks[idx]
                })

        return results

    def print_results(self, results, query):
        print(f"\n{'='*60}")
        print(f"Query: {query}")
        print(f"{'='*60}")

        if results:
            for i, r in enumerate(results, 1):
                print(f"\n[{i}] (Distance/Score: {r['distance']:.4f})")
                chunk_lines = r['chunk'].split('\n')
                for line in chunk_lines:
                    if line.startswith("[SOURCE:"):
                        print(f"    📍 {line}")
                    elif line.startswith("[หมวดหมู่:"):
                        print(f"    🏷️ {line}")
                    elif line.strip():
                        print(f"    {line}")
                print("-" * 40)
        else:
            print("No results found")


if __name__ == "__main__":
    # เพื่อนคุณสามารถรันเทสต์ไฟล์นี้ตรงๆ ได้เลย
    kb = KnowledgeBaseLoader()

    print("=" * 60)
    print("ทดสอบระบบค้นหาอัจฉริยะ (Smart Retriever)")
    print("=" * 60)
    
    try:
        # ระบบจะโหลดไฟล์ทุกอย่างอัตโนมัติในครั้งแรกที่ค้นหา
        test_queries = [
            "ปี 1 เทอม 1 ต้องเรียนวิชาอะไรบ้าง",
            "อาจารย์คนไหนเชี่ยวชาญ ML"
        ]
        
        for q in test_queries:
            results = kb.search(q, top_k=3)
            kb.print_results(results, q)

    except Exception as e:
        print(f"✗ Error: {e}")